# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_btn_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoWindow(object):
    def setupUi(self, ChoWindow):
        ChoWindow.setObjectName("ChoWindow")
        ChoWindow.resize(611, 460)
        self.centralwidget = QtWidgets.QWidget(ChoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_sis = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sis.setGeometry(QtCore.QRect(170, 50, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_sis.setFont(font)
        self.lbl_sis.setObjectName("lbl_sis")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(220, 120, 151, 41))
        self.btn_add.setObjectName("btn_add")
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(220, 170, 151, 41))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_inf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_inf.setGeometry(QtCore.QRect(220, 220, 151, 41))
        self.btn_inf.setObjectName("btn_inf")
        self.btn_remove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove.setGeometry(QtCore.QRect(220, 270, 151, 41))
        self.btn_remove.setObjectName("btn_remove")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(220, 340, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        ChoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        ChoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChoWindow)
        self.statusbar.setObjectName("statusbar")
        ChoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChoWindow)
        QtCore.QMetaObject.connectSlotsByName(ChoWindow)

    def retranslateUi(self, ChoWindow):
        _translate = QtCore.QCoreApplication.translate
        ChoWindow.setWindowTitle(_translate("ChoWindow", "MainWindow"))
        self.lbl_sis.setText(_translate("ChoWindow", "Student Information Segment"))
        self.btn_add.setText(_translate("ChoWindow", "Add Student"))
        self.btn_edit.setText(_translate("ChoWindow", "Edit Student"))
        self.btn_inf.setText(_translate("ChoWindow", "Show Information"))
        self.btn_remove.setText(_translate("ChoWindow", "Remove Student"))
        self.btn_exit.setText(_translate("ChoWindow", "Exit"))
